#pragma once
/**
 * Proactive UICC is a method of allowing a UICC to send commands to the
 * terminal (normally, the card only responds to commands sent by the terminal).
 *
 * The basic principle by which the proactive UICC feature works is by adding an
 * additional status word, namely 91XX, which is interchangeable with the 9000
 * status and indicates that a proactive command is available and has length
 * 0xXX. The terminal can fetch the command with a FETCH instruction at which
 * point it can execute it. Once the command has finished executing on the
 * terminal and a result is available, the terminal will send a TERMINAL
 * RESPONSE command with the response data.
 */

#include "common.h"
#include <stdbool.h>
#include <string.h>

typedef struct swsim_s swsim_st;

/**
 * "The type of command specifies the required interpretation of the data
 * objects which follow, and the required terminal procedure."
 * ETSI TS 102 223 V17.2.0 clause 9.4.
 */
typedef enum swsim__proactive__command_type_e
{
    SWSIM__PROACTIVE__COMMAND_TYPE__REFRESH = 0x01,
    SWSIM__PROACTIVE__COMMAND_TYPE__MORE_TIME = 0x02,
    SWSIM__PROACTIVE__COMMAND_TYPE__POLL_INTERVAL = 0x03,
    SWSIM__PROACTIVE__COMMAND_TYPE__POLLING_OFF = 0x04,
    SWSIM__PROACTIVE__COMMAND_TYPE__SET_UP_EVENT_LIST = 0x05,
    SWSIM__PROACTIVE__COMMAND_TYPE__SET_UP_CALL = 0x10,
    SWSIM__PROACTIVE__COMMAND_TYPE__SEND_SS = 0x11,
    SWSIM__PROACTIVE__COMMAND_TYPE__SEND_USSD = 0x12,
    SWSIM__PROACTIVE__COMMAND_TYPE__SEND_SHORT_MESSAGE = 0x13,
    SWSIM__PROACTIVE__COMMAND_TYPE__SEND_DTMF = 0x14,
    SWSIM__PROACTIVE__COMMAND_TYPE__LAUNCH_BROWSER = 0x15,
    SWSIM__PROACTIVE__COMMAND_TYPE__GEOGRAPHICAL_LOCATION_REQUEST = 0x16,
    SWSIM__PROACTIVE__COMMAND_TYPE__PLAY_TONE = 0x20,
    SWSIM__PROACTIVE__COMMAND_TYPE__DISPLAY_TEXT = 0x21,
    SWSIM__PROACTIVE__COMMAND_TYPE__GET_INKEY = 0x22,
    SWSIM__PROACTIVE__COMMAND_TYPE__GET_INPUT = 0x23,
    SWSIM__PROACTIVE__COMMAND_TYPE__SELECT_ITEM = 0x24,
    SWSIM__PROACTIVE__COMMAND_TYPE__SET_UP_MENU = 0x25,
    SWSIM__PROACTIVE__COMMAND_TYPE__PROVIDE_LOCAL_INFORMATION = 0x26,
    SWSIM__PROACTIVE__COMMAND_TYPE__TIMER_MANAGEMENT = 0x27,
    SWSIM__PROACTIVE__COMMAND_TYPE__SET_UP_IDLE_MODE_TEXT = 0x28,
    SWSIM__PROACTIVE__COMMAND_TYPE__PERFORM_CARD_APDU = 0x30,
    SWSIM__PROACTIVE__COMMAND_TYPE__POWER_ON_CARD = 0x31,
    SWSIM__PROACTIVE__COMMAND_TYPE__POWER_OFF_CARD = 0x32,
    SWSIM__PROACTIVE__COMMAND_TYPE__GET_READER_STATUS = 0x33,
    SWSIM__PROACTIVE__COMMAND_TYPE__RUN_AT_COMMAND = 0x34,
    SWSIM__PROACTIVE__COMMAND_TYPE__LANGUAGE_NOTIFICATION = 0x35,
    SWSIM__PROACTIVE__COMMAND_TYPE__OPEN_CHANNEL = 0x40,
    SWSIM__PROACTIVE__COMMAND_TYPE__CLOSE_CHANNEL = 0x41,
    SWSIM__PROACTIVE__COMMAND_TYPE__RECEIVE_DATA = 0x42,
    SWSIM__PROACTIVE__COMMAND_TYPE__SEND_DATA = 0x43,
    SWSIM__PROACTIVE__COMMAND_TYPE__GET_CHANNEL_STATUS = 0x44,
    SWSIM__PROACTIVE__COMMAND_TYPE__SERVICE_SEARCH = 0x45,
    SWSIM__PROACTIVE__COMMAND_TYPE__GET_SERVICE_INFORMATION = 0x46,
    SWSIM__PROACTIVE__COMMAND_TYPE__DECLARE_SERVICE = 0x47,
    SWSIM__PROACTIVE__COMMAND_TYPE__SET_FRAMES = 0x50,
    SWSIM__PROACTIVE__COMMAND_TYPE__GET_FRAMES_STATUS = 0x51,
    SWSIM__PROACTIVE__COMMAND_TYPE__RETRIEVE_MULTIMEDIA_MESSAGE = 0x60,
    SWSIM__PROACTIVE__COMMAND_TYPE__SUBMIT_MULTIMEDIA_MESSAGE = 0x61,
    SWSIM__PROACTIVE__COMMAND_TYPE__DISPLAY_MULTIMEDIA_MESSAGE = 0x62,
    SWSIM__PROACTIVE__COMMAND_TYPE__ACTIVATE = 0x70,
    SWSIM__PROACTIVE__COMMAND_TYPE__CONTACTLESS_STATE_CHANGED = 0x71,
    SWSIM__PROACTIVE__COMMAND_TYPE__COMMAND_CONTAINER = 0x72,
    SWSIM__PROACTIVE__COMMAND_TYPE__ENCAPSULATED_SESSION_CONTROL = 0x73,
    SWSIM__PROACTIVE__COMMAND_TYPE__LSI_COMMAND = 0x79,
    SWSIM__PROACTIVE__COMMAND_TYPE__END_OF_PROACTIVE_UICC_SESSION = 0x81,
} swsim__proactive__command_type_et;

/**
 * "Device for information held in the data objects which follow."
 * ETSI TS 102 223 V17.2.0 clause 8.7.
 *
 * NOTE: Some combinations are not allowed per ETSI TS 102 223 V17.2.0
 * clause 10.
 */
typedef enum swsim__proactive__device_identities__type_e
{
    SWSIM__PROACTIVE__DEVICE_IDENTITIES__KEYPAD = 0x01,
    SWSIM__PROACTIVE__DEVICE_IDENTITIES__DISPLAY = 0x02,
    SWSIM__PROACTIVE__DEVICE_IDENTITIES__EARPIECE = 0x03,
    SWSIM__PROACTIVE__DEVICE_IDENTITIES__CARD_READER_0 = 0x10,
    SWSIM__PROACTIVE__DEVICE_IDENTITIES__CARD_READER_1 = 0x11,
    SWSIM__PROACTIVE__DEVICE_IDENTITIES__CARD_READER_2 = 0x12,
    SWSIM__PROACTIVE__DEVICE_IDENTITIES__CARD_READER_3 = 0x13,
    SWSIM__PROACTIVE__DEVICE_IDENTITIES__CARD_READER_4 = 0x14,
    SWSIM__PROACTIVE__DEVICE_IDENTITIES__CARD_READER_5 = 0x15,
    SWSIM__PROACTIVE__DEVICE_IDENTITIES__CARD_READER_6 = 0x16,
    SWSIM__PROACTIVE__DEVICE_IDENTITIES__CARD_READER_7 = 0x17,
    SWSIM__PROACTIVE__DEVICE_IDENTITIES__CHANNEL_IDENTIFIER_1 = 0x21,
    SWSIM__PROACTIVE__DEVICE_IDENTITIES__CHANNEL_IDENTIFIER_2 = 0x22,
    SWSIM__PROACTIVE__DEVICE_IDENTITIES__CHANNEL_IDENTIFIER_3 = 0x23,
    SWSIM__PROACTIVE__DEVICE_IDENTITIES__CHANNEL_IDENTIFIER_4 = 0x24,
    SWSIM__PROACTIVE__DEVICE_IDENTITIES__CHANNEL_IDENTIFIER_5 = 0x25,
    SWSIM__PROACTIVE__DEVICE_IDENTITIES__CHANNEL_IDENTIFIER_6 = 0x26,
    SWSIM__PROACTIVE__DEVICE_IDENTITIES__CHANNEL_IDENTIFIER_7 = 0x27,
    SWSIM__PROACTIVE__DEVICE_IDENTITIES__ECAT_CLIENT_IDENTIFIER_1 = 0x31,
    SWSIM__PROACTIVE__DEVICE_IDENTITIES__ECAT_CLIENT_IDENTIFIER_2 = 0x32,
    SWSIM__PROACTIVE__DEVICE_IDENTITIES__ECAT_CLIENT_IDENTIFIER_3 = 0x33,
    SWSIM__PROACTIVE__DEVICE_IDENTITIES__ECAT_CLIENT_IDENTIFIER_4 = 0x34,
    SWSIM__PROACTIVE__DEVICE_IDENTITIES__ECAT_CLIENT_IDENTIFIER_5 = 0x35,
    SWSIM__PROACTIVE__DEVICE_IDENTITIES__ECAT_CLIENT_IDENTIFIER_6 = 0x36,
    SWSIM__PROACTIVE__DEVICE_IDENTITIES__ECAT_CLIENT_IDENTIFIER_7 = 0x37,
    SWSIM__PROACTIVE__DEVICE_IDENTITIES__ECAT_CLIENT_IDENTIFIER_8 = 0x38,
    SWSIM__PROACTIVE__DEVICE_IDENTITIES__ECAT_CLIENT_IDENTIFIER_9 = 0x39,
    SWSIM__PROACTIVE__DEVICE_IDENTITIES__ECAT_CLIENT_IDENTIFIER_A = 0x3A,
    SWSIM__PROACTIVE__DEVICE_IDENTITIES__ECAT_CLIENT_IDENTIFIER_B = 0x3B,
    SWSIM__PROACTIVE__DEVICE_IDENTITIES__ECAT_CLIENT_IDENTIFIER_C = 0x3C,
    SWSIM__PROACTIVE__DEVICE_IDENTITIES__ECAT_CLIENT_IDENTIFIER_D = 0x3D,
    SWSIM__PROACTIVE__DEVICE_IDENTITIES__ECAT_CLIENT_IDENTIFIER_E = 0x3E,
    SWSIM__PROACTIVE__DEVICE_IDENTITIES__ECAT_CLIENT_IDENTIFIER_F = 0x3F,
    SWSIM__PROACTIVE__DEVICE_IDENTITIES__UICC = 0x81,
    SWSIM__PROACTIVE__DEVICE_IDENTITIES__TERMINAL = 0x81,
    SWSIM__PROACTIVE__DEVICE_IDENTITIES__NETWORK = 0x83,
} swsim__proactive__device_identities__type_et;

/* ETSI TS 102 223 V17.2.0 clause.8.6. */
typedef enum swsim__proactive__command_details__command_qualifier_e
{
    // clang-format off
    SWSIM__PROACTIVE__COMMAND_DETAILS__COMMAND_QUALIFIER__REFRESH__NAA_INITIALIZATION_AND_FULL_FILE_CHANGE_NOTIFICATION = 0x00,
    SWSIM__PROACTIVE__COMMAND_DETAILS__COMMAND_QUALIFIER__REFRESH__FILE_CHANGE_NOTIFICATION = 0x01,
    SWSIM__PROACTIVE__COMMAND_DETAILS__COMMAND_QUALIFIER__REFRESH__NAA_INITIALIZATION_AND_FILE_CHANGE_NOTIFICATION = 0x02,
    SWSIM__PROACTIVE__COMMAND_DETAILS__COMMAND_QUALIFIER__REFRESH__NAA_INITIALIZATION = 0x03,
    SWSIM__PROACTIVE__COMMAND_DETAILS__COMMAND_QUALIFIER__REFRESH__UICC_RESET = 0x04,
    SWSIM__PROACTIVE__COMMAND_DETAILS__COMMAND_QUALIFIER__REFRESH__NAA_APPLICATION_RESET_3G = 0x05,
    SWSIM__PROACTIVE__COMMAND_DETAILS__COMMAND_QUALIFIER__REFRESH__NAA_SESSION_RESET_3G = 0x06,
    SWSIM__PROACTIVE__COMMAND_DETAILS__COMMAND_QUALIFIER__REFRESH__STEERING_OF_ROAMING = 0x07,
    SWSIM__PROACTIVE__COMMAND_DETAILS__COMMAND_QUALIFIER__REFRESH__STEERING_OF_ROAMING_IWLAN = 0x08,
    SWSIM__PROACTIVE__COMMAND_DETAILS__COMMAND_QUALIFIER__REFRESH__EUICC_PROFILE_STATE_CHANGE = 0x09,
    SWSIM__PROACTIVE__COMMAND_DETAILS__COMMAND_QUALIFIER__REFRESH__APPLICATION_UPDATE = 0x0A,

    SWSIM__PROACTIVE__COMMAND_DETAILS__COMMAND_QUALIFIER__MORE_TIME__RFU = 0x00,

    SWSIM__PROACTIVE__COMMAND_DETAILS__COMMAND_QUALIFIER__POLL_INTERVAL__RFU = 0x00,

    SWSIM__PROACTIVE__COMMAND_DETAILS__COMMAND_QUALIFIER__POLLLING_OFF__RFU = 0x00,

    SWSIM__PROACTIVE__COMMAND_DETAILS__COMMAND_QUALIFIER__SET_UP_CALL__IF_NOT_BUSY_ON_ANOTHER_CALL = 0x00,
    SWSIM__PROACTIVE__COMMAND_DETAILS__COMMAND_QUALIFIER__SET_UP_CALL__IF_NOT_BUSY_ON_ANOTHER_CALL_WITH_REDIAL = 0x01,
    SWSIM__PROACTIVE__COMMAND_DETAILS__COMMAND_QUALIFIER__SET_UP_CALL__PUTTING_ALL_OTHER_CALLS_ON_HOLD = 0x02,
    SWSIM__PROACTIVE__COMMAND_DETAILS__COMMAND_QUALIFIER__SET_UP_CALL__PUTTING_ALL_OTHER_CALLS_ON_HOLD_WITH_REDIAL = 0x03,
    SWSIM__PROACTIVE__COMMAND_DETAILS__COMMAND_QUALIFIER__SET_UP_CALL__DISCONNECTING_ALL_OTHER_CALLS = 0x04,
    SWSIM__PROACTIVE__COMMAND_DETAILS__COMMAND_QUALIFIER__SET_UP_CALL__DISCONNECTING_ALL_OTHER_CALLS_WITH_REDIAL = 0x05,

    SWSIM__PROACTIVE__COMMAND_DETAILS__COMMAND_QUALIFIER__SEND_DTMF_RFU = 0x00,

    SWSIM__PROACTIVE__COMMAND_DETAILS__COMMAND_QUALIFIER__SEND_SHORT_MESSAGE__00_PACKNG_NOT_REQUIRED = 0x00,
    SWSIM__PROACTIVE__COMMAND_DETAILS__COMMAND_QUALIFIER__SEND_SHORT_MESSAGE__00_SMS_PACKING_BY_TERMINAL_REQUIRED = 0x01,
    SWSIM__PROACTIVE__COMMAND_DETAILS__COMMAND_QUALIFIER__SEND_SHORT_MESSAGE__17_RFU = 0x00,

    SWSIM__PROACTIVE__COMMAND_DETAILS__COMMAND_QUALIFIER__SET_UP_EVENT_LIST__RFU = 0x00,

    SWSIM__PROACTIVE__COMMAND_DETAILS__COMMAND_QUALIFIER__PLAY_TONE__00_VIBRATE_OPTIONAL = 0x00,
    SWSIM__PROACTIVE__COMMAND_DETAILS__COMMAND_QUALIFIER__PLAY_TONE__00_VIBRATE_PREFERRED = 0x01,
    SWSIM__PROACTIVE__COMMAND_DETAILS__COMMAND_QUALIFIER__PLAY_TONE__17_RFU = 0x00,

    SWSIM__PROACTIVE__COMMAND_DETAILS__COMMAND_QUALIFIER__DISPLAY_TEXT__00_PRIORITY_NORMAL = 0x00,
    SWSIM__PROACTIVE__COMMAND_DETAILS__COMMAND_QUALIFIER__DISPLAY_TEXT__00_PRIORITY_HIGH = 0b00000001,
    SWSIM__PROACTIVE__COMMAND_DETAILS__COMMAND_QUALIFIER__DISPLAY_TEXT__16_RFU = 0x00,
    SWSIM__PROACTIVE__COMMAND_DETAILS__COMMAND_QUALIFIER__DISPLAY_TEXT__77_CLEAR_MESSAGE_AFTER_DELAY = 0x00,
    SWSIM__PROACTIVE__COMMAND_DETAILS__COMMAND_QUALIFIER__DISPLAY_TEXT__77_WAIT_FOR_USER_TO_CLEAR_MESSAGE = 0b10000000,

    SWSIM__PROACTIVE__COMMAND_DETAILS__COMMAND_QUALIFIER__GET_INKEY__00_DIGITS_ASTERISK_POUND_PLUS_ONLY = 0x00,
    SWSIM__PROACTIVE__COMMAND_DETAILS__COMMAND_QUALIFIER__GET_INKEY__00_ALPHABEST_SET = 0b00000001,
    SWSIM__PROACTIVE__COMMAND_DETAILS__COMMAND_QUALIFIER__GET_INKEY__11_SMS_DEFAULT_ALPHABET = 0x00,
    SWSIM__PROACTIVE__COMMAND_DETAILS__COMMAND_QUALIFIER__GET_INKEY__11_UCS2_ALPHABET = 0b00000010,
    SWSIM__PROACTIVE__COMMAND_DETAILS__COMMAND_QUALIFIER__GET_INKEY__22_CHARACTER_SET_DEFINITION_ENABLED = 0x00,
    SWSIM__PROACTIVE__COMMAND_DETAILS__COMMAND_QUALIFIER__GET_INKEY__22_CHARACTER_SET_DEFINITION_DISABLED_YESNO_RESPONSE_REQUESTED = 0b00000100,
    SWSIM__PROACTIVE__COMMAND_DETAILS__COMMAND_QUALIFIER__GET_INKEY__33_USER_RESPONSE_DISPLAYED = 0x00,
    SWSIM__PROACTIVE__COMMAND_DETAILS__COMMAND_QUALIFIER__GET_INKEY__33_IMMEDIATE_DIGITS_ASTERISK_POUND_PLUS_RESPONSE_REQUESTED = 0b00001000,
    SWSIM__PROACTIVE__COMMAND_DETAILS__COMMAND_QUALIFIER__GET_INKEY__46_RFU = 0x00,
    SWSIM__PROACTIVE__COMMAND_DETAILS__COMMAND_QUALIFIER__GET_INKEY__77_NO_HELP_INFORMATION_AVAILABLE = 0x00,
    SWSIM__PROACTIVE__COMMAND_DETAILS__COMMAND_QUALIFIER__GET_INKEY__77_HELP_INFORMATION_AVAILABLE = 0b10000000,

    SWSIM__PROACTIVE__COMMAND_DETAILS__COMMAND_QUALIFIER__GET_INPUT__00_DIGITS_ASTERISK_POUND_PLUS_ONLY = 0x00,
    SWSIM__PROACTIVE__COMMAND_DETAILS__COMMAND_QUALIFIER__GET_INPUT__00_ALPHABET_SET = 0b00000001,
    SWSIM__PROACTIVE__COMMAND_DETAILS__COMMAND_QUALIFIER__GET_INPUT__11_SMS_DEFAULT_ALPHABET = 0x00,
    SWSIM__PROACTIVE__COMMAND_DETAILS__COMMAND_QUALIFIER__GET_INPUT__11_UCS2_ALPHABET = 0b00000010,
    SWSIM__PROACTIVE__COMMAND_DETAILS__COMMAND_QUALIFIER__GET_INPUT__22_USER_INPUT_ECHO_ON_DISPLAY = 0x00,
    SWSIM__PROACTIVE__COMMAND_DETAILS__COMMAND_QUALIFIER__GET_INPUT__22_USER_INPUT_NOT_REVEALED = 0b00000100,
    SWSIM__PROACTIVE__COMMAND_DETAILS__COMMAND_QUALIFIER__GET_INPUT__33_USER_INPUT_IN_UNPACKED_FORMAT = 0x00,
    SWSIM__PROACTIVE__COMMAND_DETAILS__COMMAND_QUALIFIER__GET_INPUT__33_USER_INPUT_IN_SMS_PACKED_FORMAT = 0b00001000,
    SWSIM__PROACTIVE__COMMAND_DETAILS__COMMAND_QUALIFIER__GET_INPUT__46_RFU = 0x00,
    SWSIM__PROACTIVE__COMMAND_DETAILS__COMMAND_QUALIFIER__GET_INPUT__77_NO_HELP_INFORMATION_AVAILABLE = 0x00,
    SWSIM__PROACTIVE__COMMAND_DETAILS__COMMAND_QUALIFIER__GET_INPUT__77_HELP_INFORMATION_AVAILABLE = 0b10000000,

    SWSIM__PROACTIVE__COMMAND_DETAILS__COMMAND_QUALIFIER__SELECT_ITEM__00_PRESENTATION_TYPE_UNSPECIFIED = 0x00,
    SWSIM__PROACTIVE__COMMAND_DETAILS__COMMAND_QUALIFIER__SELECT_ITEM__00_PRESENTATION_TYPE_SPECIFIED = 0b00000001,
    SWSIM__PROACTIVE__COMMAND_DETAILS__COMMAND_QUALIFIER__SELECT_ITEM__11_PRESENTATION_AS_CHOICE_OF_DATA_VALUES = 0x00,
    SWSIM__PROACTIVE__COMMAND_DETAILS__COMMAND_QUALIFIER__SELECT_ITEM__11_PRESENTATION_AS_CHOICE_OF_NAVIGATION_OPTIONS = 0b00000010,
    SWSIM__PROACTIVE__COMMAND_DETAILS__COMMAND_QUALIFIER__SELECT_ITEM__22_SELECTION_PREFERENCE_NONE = 0x00,
    SWSIM__PROACTIVE__COMMAND_DETAILS__COMMAND_QUALIFIER__SELECT_ITEM__22_SELECTION_PREFERENCE_SOFT_KEY = 0b00000100,
    SWSIM__PROACTIVE__COMMAND_DETAILS__COMMAND_QUALIFIER__SELECT_ITEM__36_RFU = 0x00,
    SWSIM__PROACTIVE__COMMAND_DETAILS__COMMAND_QUALIFIER__SELECT_ITEM__77_NO_HELP_INFORMATION_AVAILABLE = 0x00,
    SWSIM__PROACTIVE__COMMAND_DETAILS__COMMAND_QUALIFIER__SELECT_ITEM__77_HELP_INFORMATION_AVAILABLE = 0b10000000,


    SWSIM__PROACTIVE__COMMAND_DETAILS__COMMAND_QUALIFIER__SET_UP_MENU__00_SELECTION_PREFERENCE_NONE = 0x00,
    SWSIM__PROACTIVE__COMMAND_DETAILS__COMMAND_QUALIFIER__SET_UP_MENU__00_SELECTION_PREFERENCE_SOFT_KEY = 0b00000001,
    SWSIM__PROACTIVE__COMMAND_DETAILS__COMMAND_QUALIFIER__SET_UP_MENU__16_RFU = 0x00,
    SWSIM__PROACTIVE__COMMAND_DETAILS__COMMAND_QUALIFIER__SET_UP_MENU__77_NO_HELP_INFORMATION_AVAILABLE = 0x00,
    SWSIM__PROACTIVE__COMMAND_DETAILS__COMMAND_QUALIFIER__SET_UP_MENU__77_HELP_INFORMATION_AVAILABLE = 0b10000000,

    SWSIM__PROACTIVE__COMMAND_DETAILS__COMMAND_QUALIFIER__PROVIDE_LOCAL_INFORMATION__LOCATION_INFORMATION_ACCORDING_TO_CURRENT_NAA = 0x00,
    SWSIM__PROACTIVE__COMMAND_DETAILS__COMMAND_QUALIFIER__PROVIDE_LOCAL_INFORMATION__TERMINAL_IMEI = 0x01,
    SWSIM__PROACTIVE__COMMAND_DETAILS__COMMAND_QUALIFIER__PROVIDE_LOCAL_INFORMATION__NETWORK_MEASUREMENT_RESULTS_ACCORDING_TO_CURRENT_NAA = 0x02,
    SWSIM__PROACTIVE__COMMAND_DETAILS__COMMAND_QUALIFIER__PROVIDE_LOCAL_INFORMATION__DATE_TIME_TIMEZONE = 0x03,
    SWSIM__PROACTIVE__COMMAND_DETAILS__COMMAND_QUALIFIER__PROVIDE_LOCAL_INFORMATION__LANGUAGE_SETTING = 0x04,
    SWSIM__PROACTIVE__COMMAND_DETAILS__COMMAND_QUALIFIER__PROVIDE_LOCAL_INFORMATION__GSM_RESERVED = 0x05,
    SWSIM__PROACTIVE__COMMAND_DETAILS__COMMAND_QUALIFIER__PROVIDE_LOCAL_INFORMATION__ACCESS_TECHNOLOGY_SINGLE_ACCESS = 0x06,
    SWSIM__PROACTIVE__COMMAND_DETAILS__COMMAND_QUALIFIER__PROVIDE_LOCAL_INFORMATION__TERMINAL_ESN = 0x07,
    SWSIM__PROACTIVE__COMMAND_DETAILS__COMMAND_QUALIFIER__PROVIDE_LOCAL_INFORMATION__TERMINAL_IMEISV = 0x08,
    SWSIM__PROACTIVE__COMMAND_DETAILS__COMMAND_QUALIFIER__PROVIDE_LOCAL_INFORMATION__SEARCH_MODE = 0x09,
    SWSIM__PROACTIVE__COMMAND_DETAILS__COMMAND_QUALIFIER__PROVIDE_LOCAL_INFORMATION__CHARGE_STATE_OF_BATTERY = 0x0A,
    SWSIM__PROACTIVE__COMMAND_DETAILS__COMMAND_QUALIFIER__PROVIDE_LOCAL_INFORMATION__TERMINAL_MEID = 0x0B,
    SWSIM__PROACTIVE__COMMAND_DETAILS__COMMAND_QUALIFIER__PROVIDE_LOCAL_INFORMATION__WSID_CURRENT = 0x0C,
    SWSIM__PROACTIVE__COMMAND_DETAILS__COMMAND_QUALIFIER__PROVIDE_LOCAL_INFORMATION__BROADCAST_NETWORK_INFORMATION_ACCORDING_TO_CURRENT_BROADCAST_NETWORK_TECHNOLOGY_USED = 0x0D,
    SWSIM__PROACTIVE__COMMAND_DETAILS__COMMAND_QUALIFIER__PROVIDE_LOCAL_INFORMATION__MULTIPLE_ACCESS_TECHNOLOGIES = 0x0E,
    SWSIM__PROACTIVE__COMMAND_DETAILS__COMMAND_QUALIFIER__PROVIDE_LOCAL_INFORMATION__LOCAL_INFORMATION_FOR_MULTIPLE_ACCESS_TECHNOLOGIES = 0x0F,
    SWSIM__PROACTIVE__COMMAND_DETAILS__COMMAND_QUALIFIER__PROVIDE_LOCAL_INFORMATION__NETWORK_MEASUREMENT_RESULTS_FOR_MULTIPLE_ACCESS_TECHNOLOGIES = 0x10,
    SWSIM__PROACTIVE__COMMAND_DETAILS__COMMAND_QUALIFIER__PROVIDE_LOCAL_INFORMATION__CSG_ID_LIST_AND_CORRESPONDING_HNB_NAME = 0x11,
    SWSIM__PROACTIVE__COMMAND_DETAILS__COMMAND_QUALIFIER__PROVIDE_LOCAL_INFORMATION__HENB_IP_ADDRESS = 0x12,
    SWSIM__PROACTIVE__COMMAND_DETAILS__COMMAND_QUALIFIER__PROVIDE_LOCAL_INFORMATION__HENB_SURROUNDING_MACROCELLS = 0x13,
    SWSIM__PROACTIVE__COMMAND_DETAILS__COMMAND_QUALIFIER__PROVIDE_LOCAL_INFORMATION__WLAN_IDENTIFIER_CURRENT = 0x14,
    SWSIM__PROACTIVE__COMMAND_DETAILS__COMMAND_QUALIFIER__PROVIDE_LOCAL_INFORMATION__SLICES_INFORMATION = 0x15,
    SWSIM__PROACTIVE__COMMAND_DETAILS__COMMAND_QUALIFIER__PROVIDE_LOCAL_INFORMATION__CAG_INFORMATION_LIST_AND_CORRESPONDING_HUMAND_READABLE_NETWORK_NAME_PER_CAG_ID = 0x16,
    SWSIM__PROACTIVE__COMMAND_DETAILS__COMMAND_QUALIFIER__PROVIDE_LOCAL_INFORMATION__SUPPORTED_RADIO_ACCESS_TECHNOLOGIES = 0x1A,

    SWSIM__PROACTIVE__COMMAND_DETAILS__COMMAND_QUALIFIER__SET_UP_IDLE_MODE_TEXT__RFU = 0x00,

    SWSIM__PROACTIVE__COMMAND_DETAILS__COMMAND_QUALIFIER__PERFORM_CARD_APDU__RFU = 0x00,

    SWSIM__PROACTIVE__COMMAND_DETAILS__COMMAND_QUALIFIER__POWER_OFF_CARD__RFU = 0x00,

    SWSIM__PROACTIVE__COMMAND_DETAILS__COMMAND_QUALIFIER__POWER_ON_CARD__RFU = 0x00,

    SWSIM__PROACTIVE__COMMAND_DETAILS__COMMAND_QUALIFIER__GET_READER_STATUS__CARD_READER_STATUS = 0x00,
    SWSIM__PROACTIVE__COMMAND_DETAILS__COMMAND_QUALIFIER__GET_READER_STATUS__CARD_READER_IDENTIFIER = 0x01,

    SWSIM__PROACTIVE__COMMAND_DETAILS__COMMAND_QUALIFIER__TIMER_MANAGEMENT__01_START = 0x00,
    SWSIM__PROACTIVE__COMMAND_DETAILS__COMMAND_QUALIFIER__TIMER_MANAGEMENT__01_DEACTIVATE = 0x01,
    SWSIM__PROACTIVE__COMMAND_DETAILS__COMMAND_QUALIFIER__TIMER_MANAGEMENT__01_GET_CURRENT_VALUE = 0x10,
    SWSIM__PROACTIVE__COMMAND_DETAILS__COMMAND_QUALIFIER__TIMER_MANAGEMENT__27_RFU = 0x00,

    SWSIM__PROACTIVE__COMMAND_DETAILS__COMMAND_QUALIFIER__RUN_AT_COMMAND__RFU = 0x00,

    SWSIM__PROACTIVE__COMMAND_DETAILS__COMMAND_QUALIFIER__LANGUAGE_NOTIFICATION__00_NONSPECIFIC_LANGUAGE_NOTIFICATION = 0x00,
    SWSIM__PROACTIVE__COMMAND_DETAILS__COMMAND_QUALIFIER__LANGUAGE_NOTIFICATION__00_SPECIFIC_LANGUAGE_NOTIFICATION = 0b00000001,
    SWSIM__PROACTIVE__COMMAND_DETAILS__COMMAND_QUALIFIER__LANGUAGE_NOTIFICATION__17_RFU = 0x00,

    SWSIM__PROACTIVE__COMMAND_DETAILS__COMMAND_QUALIFIER__LAUNCH_BROWSER__LAUNCH_BROWSER_IF_NOT_ALREADY_LAUNCHED = 0x00,
    SWSIM__PROACTIVE__COMMAND_DETAILS__COMMAND_QUALIFIER__LAUNCH_BROWSER__USE_EXISTING_BROWSER_WITHOUT_USING_EXISTING_SECURED_SESSION = 0x02,
    SWSIM__PROACTIVE__COMMAND_DETAILS__COMMAND_QUALIFIER__LAUNCH_BROWSER__CLOSE_EXISTING_BROWSER_SESSION_AND_LAUNCH_NEW_BROWSER_SESSION = 0x03,

    /* OPEN CHANNEL for CS, packet data serice, local and default (network) bearer. */
    SWSIM__PROACTIVE__COMMAND_DETAILS__COMMAND_QUALIFIER__OPEN_CHANNEL_ELSE__00_ON_DEMAND_LINK_ESTABLISHMENT = 0x00,
    SWSIM__PROACTIVE__COMMAND_DETAILS__COMMAND_QUALIFIER__OPEN_CHANNEL_ELSE__00_IMMEDIATE_LINK_ESTABLISHMENT = 0b00000001,
    SWSIM__PROACTIVE__COMMAND_DETAILS__COMMAND_QUALIFIER__OPEN_CHANNEL_ELSE__11_NO_AUTOMATIC_RECONNECTION = 0x00,
    SWSIM__PROACTIVE__COMMAND_DETAILS__COMMAND_QUALIFIER__OPEN_CHANNEL_ELSE__11_AUTOMATIC_RECONNECTION = 0b00000010,
    SWSIM__PROACTIVE__COMMAND_DETAILS__COMMAND_QUALIFIER__OPEN_CHANNEL_ELSE__22_NO_BACKGROUND_MODE = 0x00,
    SWSIM__PROACTIVE__COMMAND_DETAILS__COMMAND_QUALIFIER__OPEN_CHANNEL_ELSE__22_IMMEDIATE_LINK_ESTABLISHMENT_IN_BACKGROUND_MODE = 0b00000100,
    SWSIM__PROACTIVE__COMMAND_DETAILS__COMMAND_QUALIFIER__OPEN_CHANNEL_ELSE__33_NO_DNS_SERVER_ADDRESSES_REQUESTED = 0x00,
    SWSIM__PROACTIVE__COMMAND_DETAILS__COMMAND_QUALIFIER__OPEN_CHANNEL_ELSE__33_DNS_SERVER_ADDRESSES_REQUESTED = 0b00001000, /* Only for packet data service. */

    SWSIM__PROACTIVE__COMMAND_DETAILS__COMMAND_QUALIFIER__OPEN_CHANNEL_UICC_SERVER_MODE__RFU = 0x00,

    SWSIM__PROACTIVE__COMMAND_DETAILS__COMMAND_QUALIFIER__OPEN_CHANNEL_TERMINAL_SERVER_MODE__00_LAUNCH_APPLICATION_IMMEDIATELY_WITHOUT_ADDITIONAL_LAUNCH_PARAMETERS = 0x00,
    SWSIM__PROACTIVE__COMMAND_DETAILS__COMMAND_QUALIFIER__OPEN_CHANNEL_TERMINAL_SERVER_MODE__00_LAUNCH_PARAMETERS_FOLLOWING = 0b00000001,
    SWSIM__PROACTIVE__COMMAND_DETAILS__COMMAND_QUALIFIER__OPEN_CHANNEL_TERMINAL_SERVER_MODE__17_RFU = 0x00,

    /* CLOSE CHANNEL for CS, local and default (network) bearer. */
    SWSIM__PROACTIVE__COMMAND_DETAILS__COMMAND_QUALIFIER__CLOSE_CHANNEL_ELSE__RFU = 0x00,

    SWSIM__PROACTIVE__COMMAND_DETAILS__COMMAND_QUALIFIER__CLOSE_CHANNEL_PACKET_DATA_SERVICE__00_NO_INDICATION = 0x00,
    SWSIM__PROACTIVE__COMMAND_DETAILS__COMMAND_QUALIFIER__CLOSE_CHANNEL_PACKET_DATA_SERVICE__00_INDICATION_TO_TERMINAL_THAT_NEXT_CAT_COMMAND_WILL_BE_OPEN_CHANNEL_USING_SAME_NETWORK_ACCESS_NAME_AND_BEARER_DESCRIPTION_AS_CHANNEL_TO_BE_CLOSED = 0b00000001,
    SWSIM__PROACTIVE__COMMAND_DETAILS__COMMAND_QUALIFIER__CLOSE_CHANNEL_PACKET_DATA_SERVICE__17_RFU = 0x00,

    SWSIM__PROACTIVE__COMMAND_DETAILS__COMMAND_QUALIFIER__CLOSE_CHANNEL_UICC_SERVER_MODE__00_CLOSE_THE_TCP_CONNECTION_AND_GO_TO_TCP_IN_CLOSED_STATE = 0x00,
    SWSIM__PROACTIVE__COMMAND_DETAILS__COMMAND_QUALIFIER__CLOSE_CHANNEL_UICC_SERVER_MODE__00_CLOSE_THE_TCP_CONNECTION_AND_GO_TO_TCP_IN_LISTEN_STATE = 0b00000001,
    SWSIM__PROACTIVE__COMMAND_DETAILS__COMMAND_QUALIFIER__CLOSE_CHANNEL_UICC_SERVER_MODE__17_RFU = 0x00,

    SWSIM__PROACTIVE__COMMAND_DETAILS__COMMAND_QUALIFIER__RECEIVE_DATA__RFU = 0x00,

    SWSIM__PROACTIVE__COMMAND_DETAILS__COMMAND_QUALIFIER__SEND_DATA__00_STORE_DATA_IN_TX_BUFFER = 0x00,
    SWSIM__PROACTIVE__COMMAND_DETAILS__COMMAND_QUALIFIER__SEND_DATA__00_SEND_DATA_IMMEDIATELY = 0b00000001,
    SWSIM__PROACTIVE__COMMAND_DETAILS__COMMAND_QUALIFIER__SEND_DATA__17_RFU = 0x00,

    SWSIM__PROACTIVE__COMMAND_DETAILS__COMMAND_QUALIFIER__GET_CHANNEL_STATUS__RFU = 0x00,

    SWSIM__PROACTIVE__COMMAND_DETAILS__COMMAND_QUALIFIER__SERVICE_SEARCH__RFU = 0x00,

    SWSIM__PROACTIVE__COMMAND_DETAILS__COMMAND_QUALIFIER__GET_SERVICE_INFORMATION__RFU = 0x00,

    SWSIM__PROACTIVE__COMMAND_DETAILS__COMMAND_QUALIFIER__DECLARE_SERVICE__00_ADD_A_NEW_SERVICE_TO_THE_TERMINAL_SERVICE_DATABASE = 0x00,
    SWSIM__PROACTIVE__COMMAND_DETAILS__COMMAND_QUALIFIER__DECLARE_SERVICE__00_DELETE_A_SERVICE_FROM_THE_TERMINAL_SERVICE_DATABASE = 0b00000001,
    SWSIM__PROACTIVE__COMMAND_DETAILS__COMMAND_QUALIFIER__DECLARE_SERVICE__17_RFU = 0x00,

    SWSIM__PROACTIVE__COMMAND_DETAILS__COMMAND_QUALIFIER__SET_FRAMES__DRAW_SEPARATOR_BETWEEN_EVERY_ADJOINING_FRAME = 0x00,
    SWSIM__PROACTIVE__COMMAND_DETAILS__COMMAND_QUALIFIER__SET_FRAMES__DO_NOT_DRAW_SEPARATOR_BETWEEN_EVERY_ADJOINING_FRAME = 0x01,

    SWSIM__PROACTIVE__COMMAND_DETAILS__COMMAND_QUALIFIER__GET_FRAME_STATUS__RFU = 0x00,

    SWSIM__PROACTIVE__COMMAND_DETAILS__COMMAND_QUALIFIER__DISPLAY_MULTIMEDIA_MESSAGE__00_NORMAL_PRIORITY = 0x00,
    SWSIM__PROACTIVE__COMMAND_DETAILS__COMMAND_QUALIFIER__DISPLAY_MULTIMEDIA_MESSAGE__00_HIGH_PRIORITY = 0b00000001,
    SWSIM__PROACTIVE__COMMAND_DETAILS__COMMAND_QUALIFIER__DISPLAY_MULTIMEDIA_MESSAGE__16_RFU = 0x00,
    SWSIM__PROACTIVE__COMMAND_DETAILS__COMMAND_QUALIFIER__DISPLAY_MULTIMEDIA_MESSAGE__77_CLEAR_MESSAGE_AFTER_DELAY = 0x00,
    SWSIM__PROACTIVE__COMMAND_DETAILS__COMMAND_QUALIFIER__DISPLAY_MULTIMEDIA_MESSAGE__77_WAIT_FOR_USER_TO_CLEAR_MESSAGE = 0b10000000,

    SWSIM__PROACTIVE__COMMAND_DETAILS__COMMAND_QUALIFIER__ACTIVATE__RFU = 0x00,

    SWSIM__PROACTIVE__COMMAND_DETAILS__COMMAND_QUALIFIER__CONTACTLESS_STATE_CHANGED__RFU = 0x00,

    SWSIM__PROACTIVE__COMMAND_DETAILS__COMMAND_QUALIFIER__COMMAND_CONTAINER__RFU = 0x00,

    SWSIM__PROACTIVE__COMMAND_DETAILS__COMMAND_QUALIFIER__ENCAPSULATED_SESSION_CONTROL__END_ENSCAPSULATED_COMMAND_SESSION = 0x00,
    SWSIM__PROACTIVE__COMMAND_DETAILS__COMMAND_QUALIFIER__ENCAPSULATED_SESSION_CONTROL__REQUEST_MASTER_SA_SETUP = 0x01,
    SWSIM__PROACTIVE__COMMAND_DETAILS__COMMAND_QUALIFIER__ENCAPSULATED_SESSION_CONTROL__REQUEST_CONNECTION_SA_SETUP = 0x02,
    SWSIM__PROACTIVE__COMMAND_DETAILS__COMMAND_QUALIFIER__ENCAPSULATED_SESSION_CONTROL__REQUEST_SECURE_CHANNEL_START = 0x03,
    SWSIM__PROACTIVE__COMMAND_DETAILS__COMMAND_QUALIFIER__ENCAPSULATED_SESSION_CONTROL__CLOSE_MASTER_AND_CONNECTION_SA_KEEP_ENCAPSULATED_COMMAND_SESSION = 0x04,

    SWSIM__PROACTIVE__COMMAND_DETAILS__COMMAND_QUALIFIER__LIST_COMMAND__PROACTIVE_SESSION_REQUEST = 0x00,
    SWSIM__PROACTIVE__COMMAND_DETAILS__COMMAND_QUALIFIER__LIST_COMMAND__UICC_PLATFORM_RESET = 0x01,
    // clang-format on
} swsim__proactive__command_details__command_qualifier_et;

/* ETSI TS 102 223 V17.2.0 clause.8.31. */
typedef enum swsim__proactive__icon_identifier__icon_qualifier_e
{
    // clang-format off
    SWSIM__PROACTIVE__ICON_IDENTIFIER__ICON_QUALIFIER__00_ICON_IS_SELF_EXPLANATORY = 0x00,
    SWSIM__PROACTIVE__ICON_IDENTIFIER__ICON_QUALIFIER__00_ICON_IS_NOT_SELF_EXPLANATORY = 0b00000001,
    SWSIM__PROACTIVE__ICON_IDENTIFIER__ICON_QUALIFIER__17_RFU = 0x00,
    // clang-format on
} swsim__proactive__icon_identifier__icon_qualifier_et;

/* ETSI TS 102 223 V17.2.0 clause.8.8. */
typedef enum swsim__proactive__duration__time_unit_e
{
    // clang-format off
    SWSIM__PROACTIVE__DURATION__TIME_UNIT__MINUTES = 0x00,
    SWSIM__PROACTIVE__DURATION__TIME_UNIT__SECONDS = 0x01,
    SWSIM__PROACTIVE__DURATION__TIME_UNIT__TENTHS_OF_SECONDS = 0x02,
    // clang-format on
} swsim__proactive__duration__time_unit_et;

/**
 * ETSI TS 102 223 V17.2.0 clause.8.15.0.
 * NOTE: There are other options defined in ETSI TS 123 038 but these are
 * recommended.
 */
typedef enum swsim__proactive__text_string__data_coding_scheme_e
{
    // clang-format off
    SWSIM__PROACTIVE__TEXT_STRING__DATA_CODING_SCHEME__GSM_DEFAULT_ALPHABET_7BIT_PACKED = 0x00,
    SWSIM__PROACTIVE__TEXT_STRING__DATA_CODING_SCHEME__GSM_DEFAULT_ALPHABET_8BIT = 0x04,
    SWSIM__PROACTIVE__TEXT_STRING__DATA_CODING_SCHEME__UCS2 = 0x08,
    // clang-format on
} swsim__proactive__text_string__data_coding_scheme_et;

/* ETSI TS 123 040 V17.3.0 clause 9.2.3.24.10.1.1. */
typedef enum swsim__proactive__text_attribute__formatting_style_e
{
    // clang-format off
    SWSIM__PROACTIVE__TEXT_ATTRIBUTE__FORMATTING_STYLE__00_ALIGNMENT_LEFT = 0b00000000,
    SWSIM__PROACTIVE__TEXT_ATTRIBUTE__FORMATTING_STYLE__00_ALIGNMENT_CENTER = 0b00000001,
    SWSIM__PROACTIVE__TEXT_ATTRIBUTE__FORMATTING_STYLE__00_ALIGNMENT_RIGHT = 0b00000010,
    SWSIM__PROACTIVE__TEXT_ATTRIBUTE__FORMATTING_STYLE__00_ALIGNMENT_LANGUAGE_SPECIFIC = 0b00000011, /* Default */

    SWSIM__PROACTIVE__TEXT_ATTRIBUTE__FORMATTING_STYLE__12_FONT_SIZE_NORMAL = 0b00000000, /* Default */
    SWSIM__PROACTIVE__TEXT_ATTRIBUTE__FORMATTING_STYLE__12_FONT_SIZE_LARGE = 0b00000100,
    SWSIM__PROACTIVE__TEXT_ATTRIBUTE__FORMATTING_STYLE__12_FONT_SIZE_SMALL = 0b00001000,

    SWSIM__PROACTIVE__TEXT_ATTRIBUTE__FORMATTING_STYLE__33_STYLE_BOLD_ON = 0b00010000,
    SWSIM__PROACTIVE__TEXT_ATTRIBUTE__FORMATTING_STYLE__33_STYLE_BOLD_OFF = 0b00000000,

    SWSIM__PROACTIVE__TEXT_ATTRIBUTE__FORMATTING_STYLE__44_STYLE_ITALIC_ON = 0b00100000,
    SWSIM__PROACTIVE__TEXT_ATTRIBUTE__FORMATTING_STYLE__44_STYLE_ITALIC_OFF = 0b00000000,

    SWSIM__PROACTIVE__TEXT_ATTRIBUTE__FORMATTING_STYLE__55_STYLE_UNDERLINED_ON = 0b01000000,
    SWSIM__PROACTIVE__TEXT_ATTRIBUTE__FORMATTING_STYLE__55_STYLE_UNDERLINED_OFF = 0b00000000,

    SWSIM__PROACTIVE__TEXT_ATTRIBUTE__FORMATTING_STYLE__66_STYLE_STRIKETHROUGH_ON = 0b10000000,
    SWSIM__PROACTIVE__TEXT_ATTRIBUTE__FORMATTING_STYLE__66_STYLE_STRIKETHROUGH_OFF = 0b00000000,
    // clang-format on
} swsim__proactive__text_attribute__formatting_style_et;

/* ETSI TS 123 040 V17.3.0 clause 9.2.3.24.10.1.1. */
typedef enum swsim__proactive__text_attribute__formatting_color_e
{
    // clang-format off
    SWSIM__PROACTIVE__TEXT_ATTRIBUTE__FORMATTING_COLOR__FG_BLACK = 0x00,
    SWSIM__PROACTIVE__TEXT_ATTRIBUTE__FORMATTING_COLOR__FG_DARK_GREY = 0b0001,
    SWSIM__PROACTIVE__TEXT_ATTRIBUTE__FORMATTING_COLOR__FG_DARK_RED = 0b0010,
    SWSIM__PROACTIVE__TEXT_ATTRIBUTE__FORMATTING_COLOR__FG_DARK_YELLOW = 0b0011,
    SWSIM__PROACTIVE__TEXT_ATTRIBUTE__FORMATTING_COLOR__FG_DARK_GREEN = 0b0100,
    SWSIM__PROACTIVE__TEXT_ATTRIBUTE__FORMATTING_COLOR__FG_DARK_CYAN = 0b0101,
    SWSIM__PROACTIVE__TEXT_ATTRIBUTE__FORMATTING_COLOR__FG_DARK_BLUE = 0b0110,
    SWSIM__PROACTIVE__TEXT_ATTRIBUTE__FORMATTING_COLOR__FG_DARK_MAGENTA = 0b0111,
    SWSIM__PROACTIVE__TEXT_ATTRIBUTE__FORMATTING_COLOR__FG_GREY = 0b1000,
    SWSIM__PROACTIVE__TEXT_ATTRIBUTE__FORMATTING_COLOR__FG_WHITE = 0b1001,
    SWSIM__PROACTIVE__TEXT_ATTRIBUTE__FORMATTING_COLOR__FG_BRIGHT_RED = 0b1010,
    SWSIM__PROACTIVE__TEXT_ATTRIBUTE__FORMATTING_COLOR__FG_BRIGHT_YELLOW = 0b1011,
    SWSIM__PROACTIVE__TEXT_ATTRIBUTE__FORMATTING_COLOR__FG_BRIGHT_GREEN = 0b1100,
    SWSIM__PROACTIVE__TEXT_ATTRIBUTE__FORMATTING_COLOR__FG_BRIGHT_CYAN = 0b1101,
    SWSIM__PROACTIVE__TEXT_ATTRIBUTE__FORMATTING_COLOR__FG_BRIGHT_BLUE = 0b1110,
    SWSIM__PROACTIVE__TEXT_ATTRIBUTE__FORMATTING_COLOR__FG_BRIGHT_MAGENTA = 0b1111,

    SWSIM__PROACTIVE__TEXT_ATTRIBUTE__FORMATTING_COLOR__BG_BLACK = SWSIM__PROACTIVE__TEXT_ATTRIBUTE__FORMATTING_COLOR__FG_BLACK << 4,
    SWSIM__PROACTIVE__TEXT_ATTRIBUTE__FORMATTING_COLOR__BG_DARK_GREY = SWSIM__PROACTIVE__TEXT_ATTRIBUTE__FORMATTING_COLOR__FG_DARK_GREY << 4,
    SWSIM__PROACTIVE__TEXT_ATTRIBUTE__FORMATTING_COLOR__BG_DARK_RED = SWSIM__PROACTIVE__TEXT_ATTRIBUTE__FORMATTING_COLOR__FG_DARK_RED << 4,
    SWSIM__PROACTIVE__TEXT_ATTRIBUTE__FORMATTING_COLOR__BG_DARK_YELLOW = SWSIM__PROACTIVE__TEXT_ATTRIBUTE__FORMATTING_COLOR__FG_DARK_YELLOW << 4,
    SWSIM__PROACTIVE__TEXT_ATTRIBUTE__FORMATTING_COLOR__BG_DARK_GREEN = SWSIM__PROACTIVE__TEXT_ATTRIBUTE__FORMATTING_COLOR__FG_DARK_GREEN << 4,
    SWSIM__PROACTIVE__TEXT_ATTRIBUTE__FORMATTING_COLOR__BG_DARK_CYAN = SWSIM__PROACTIVE__TEXT_ATTRIBUTE__FORMATTING_COLOR__FG_DARK_CYAN << 4,
    SWSIM__PROACTIVE__TEXT_ATTRIBUTE__FORMATTING_COLOR__BG_DARK_BLUE = SWSIM__PROACTIVE__TEXT_ATTRIBUTE__FORMATTING_COLOR__FG_DARK_BLUE << 4,
    SWSIM__PROACTIVE__TEXT_ATTRIBUTE__FORMATTING_COLOR__BG_DARK_MAGENTA = SWSIM__PROACTIVE__TEXT_ATTRIBUTE__FORMATTING_COLOR__FG_DARK_MAGENTA << 4,
    SWSIM__PROACTIVE__TEXT_ATTRIBUTE__FORMATTING_COLOR__BG_GREY = SWSIM__PROACTIVE__TEXT_ATTRIBUTE__FORMATTING_COLOR__FG_GREY << 4,
    SWSIM__PROACTIVE__TEXT_ATTRIBUTE__FORMATTING_COLOR__BG_WHITE = SWSIM__PROACTIVE__TEXT_ATTRIBUTE__FORMATTING_COLOR__FG_WHITE << 4,
    SWSIM__PROACTIVE__TEXT_ATTRIBUTE__FORMATTING_COLOR__BG_BRIGHT_RED = SWSIM__PROACTIVE__TEXT_ATTRIBUTE__FORMATTING_COLOR__FG_BRIGHT_RED << 4,
    SWSIM__PROACTIVE__TEXT_ATTRIBUTE__FORMATTING_COLOR__BG_BRIGHT_YELLOW = SWSIM__PROACTIVE__TEXT_ATTRIBUTE__FORMATTING_COLOR__FG_BRIGHT_YELLOW << 4,
    SWSIM__PROACTIVE__TEXT_ATTRIBUTE__FORMATTING_COLOR__BG_BRIGHT_GREEN = SWSIM__PROACTIVE__TEXT_ATTRIBUTE__FORMATTING_COLOR__FG_BRIGHT_GREEN << 4,
    SWSIM__PROACTIVE__TEXT_ATTRIBUTE__FORMATTING_COLOR__BG_BRIGHT_CYAN = SWSIM__PROACTIVE__TEXT_ATTRIBUTE__FORMATTING_COLOR__FG_BRIGHT_CYAN << 4,
    SWSIM__PROACTIVE__TEXT_ATTRIBUTE__FORMATTING_COLOR__BG_BRIGHT_BLUE = SWSIM__PROACTIVE__TEXT_ATTRIBUTE__FORMATTING_COLOR__FG_BRIGHT_BLUE << 4,
    SWSIM__PROACTIVE__TEXT_ATTRIBUTE__FORMATTING_COLOR__BG_BRIGHT_MAGENTA = SWSIM__PROACTIVE__TEXT_ATTRIBUTE__FORMATTING_COLOR__FG_BRIGHT_MAGENTA << 4,
    // clang-format on
} swsim__proactive__text_attribute__color_et;

/* ETSI TS 102 223 V17.2.0 clause.8.47. */
typedef enum swsim__proactive__browser_identity__browser_identity_e
{
    // clang-format off
    SWSIM__PROACTIVE__BROWSER_IDENTITY__BROWSER_IDENTITY__DEFAULT_BROWSER = 0x00,
    SWSIM__PROACTIVE__BROWSER_IDENTITY__BROWSER_IDENTITY__WML_BROWSER = 0x01,
    SWSIM__PROACTIVE__BROWSER_IDENTITY__BROWSER_IDENTITY__HTML_BROWSER = 0x02,
    SWSIM__PROACTIVE__BROWSER_IDENTITY__BROWSER_IDENTITY__XHTML_BROWSER = 0x03,
    SWSIM__PROACTIVE__BROWSER_IDENTITY__BROWSER_IDENTITY__CHTML_BROWSER = 0x04,
    // clang-format on
} swsim__proactive__browser_identity__browser_identity_et;

/* ETSI TS 102 223 V17.2.0 clause.8.49. */
typedef enum swsim__proactive__bearer__bearer_e
{
    SWSIM__PROACTIVE__BEARER__BEARER__SHORT_MESSAGE = 0x00,
    SWSIM__PROACTIVE__BEARER__BEARER__CIRCUIT_SWITCHED_DATA = 0x01,
    SWSIM__PROACTIVE__BEARER__BEARER__GSM_3G_RESERVED = 0x02,
    SWSIM__PROACTIVE__BEARER__BEARER__PACKET_SWITCHED = 0x03,
} swsim__proactive__bearer__bearer_et;

/* ETSI TS 102 223 V17.2.0 clause.8.32. */
typedef enum swsim__proactive__item_icon_identifier_list__icon_list_qualifier_e
{
    // clang-format off
    SWSIM__PROACTIVE__ITEM_ICON_IDENTIFIER_LIST__ICON_LIST_QUALIFIER__00_ICON_IS_SELF_EXPLANATORY = 0x00,
    SWSIM__PROACTIVE__ITEM_ICON_IDENTIFIER_LIST__ICON_LIST_QUALIFIER__00_ICON_IS_NOT_SELF_EXPLANATORY = 0b00000001,
    SWSIM__PROACTIVE__ITEM_ICON_IDENTIFIER_LIST__ICON_LIST_QUALIFIER__17_RFU = 0x00,
    // clang-format on
} swsim__proactive__item_icon_identifier_list__icon_list_qualifier_et;

/* ETSI TS 102 223 V17.2.0 clause.8.16. */
typedef enum swsim__proactive__tone__tone_e
{
    // clang-format off
    SWSIM__PROACTIVE__TONE__TONE__STANDARD_SUPERVISORY_DIAL_TONE = 0x01,
    SWSIM__PROACTIVE__TONE__TONE__STANDARD_SUPERVISORY_CALLED_SUBSCRIBER_BUSY = 0x02,
    SWSIM__PROACTIVE__TONE__TONE__STANDARD_SUPERVISORY_CONGESTION = 0x03,
    SWSIM__PROACTIVE__TONE__TONE__STANDARD_SUPERVISORY_RADIO_PATH_ACKNOWLEDGE = 0x04,
    SWSIM__PROACTIVE__TONE__TONE__STANDARD_SUPERVISORY_RADIO_PATH_NOT_AVAILABLE_CALL_DROPPED = 0x05,
    SWSIM__PROACTIVE__TONE__TONE__STANDARD_SUPERVISORY_ERROR_SPECIAL_INFORMATION = 0x06,
    SWSIM__PROACTIVE__TONE__TONE__STANDARD_SUPERVISORY_CALL_WAITING_TONE = 0x07,
    SWSIM__PROACTIVE__TONE__TONE__STANDARD_SUPERVISORY_RINGING_TONE = 0x08,

    SWSIM__PROACTIVE__TONE__TONE__TERMINAL_PROPRIETARY_GENERAL_BEEP = 0x10,
    SWSIM__PROACTIVE__TONE__TONE__TERMINAL_PROPRIETARY_POSITIVE_ACKNOWLEDGEMENT_TONE = 0x11,
    SWSIM__PROACTIVE__TONE__TONE__TERMINAL_PROPRIETARY_NEGATIVE_ACKNOWLEDGEMENT_TONE = 0x12,
    SWSIM__PROACTIVE__TONE__TONE__TERMINAL_PROPRIETARY_RINGING_TONE_USER_DEFINED = 0x13,
    SWSIM__PROACTIVE__TONE__TONE__TERMINAL_PROPRIETARY_ALERT_TONE_USER_DEFINED = 0x14,
    SWSIM__PROACTIVE__TONE__TONE__TERMINAL_PROPRIETARY_CRITICAL_ALERT = 0x15,
    SWSIM__PROACTIVE__TONE__TONE__TERMINAL_PROPRIETARY_VIBRATE = 0x20,

    SWSIM__PROACTIVE__TONE__TONE__THEMED_HAPPY_TONE = 0x30,
    SWSIM__PROACTIVE__TONE__TONE__THEMED_SAD_TONE = 0x31,
    SWSIM__PROACTIVE__TONE__TONE__THEMED_URGENT_ACTION_TONE = 0x32,
    SWSIM__PROACTIVE__TONE__TONE__THEMED_QUESTION_TONE = 0x33,
    SWSIM__PROACTIVE__TONE__TONE__THEMED_MESSAGE_RECEIVED_TONE = 0x34,

    SWSIM__PROACTIVE__TONE__TONE__MELODY_1 = 0x40,
    SWSIM__PROACTIVE__TONE__TONE__MELODY_2 = 0x41,
    SWSIM__PROACTIVE__TONE__TONE__MELODY_3 = 0x42,
    SWSIM__PROACTIVE__TONE__TONE__MELODY_4 = 0x43,
    SWSIM__PROACTIVE__TONE__TONE__MELODY_5 = 0x44,
    SWSIM__PROACTIVE__TONE__TONE__MELODY_6 = 0x45,
    SWSIM__PROACTIVE__TONE__TONE__MELODY_7 = 0x46,
    SWSIM__PROACTIVE__TONE__TONE__MELODY_8 = 0x47,
    // clang-format on
} swsim__proactive__tone__tone_et;

/* ETSI TS 102 223 V17.2.0 clause.8.52. */
typedef enum swsim__proactive__bearer_description__bearer_type_e
{
    // clang-format off
    SWSIM__PROACTIVE__BEARER_DESCRIPTION__BEARER_TYPE__RESERVED_GSM_3GPP_0 = 0x01,
    SWSIM__PROACTIVE__BEARER_DESCRIPTION__BEARER_TYPE__RESERVED_GSM_3GPP_1 = 0x02,
    SWSIM__PROACTIVE__BEARER_DESCRIPTION__BEARER_TYPE__DEFAULT_BEARER_FOR_REQUESTED_TRANSPORT_LAYER = 0x03,
    SWSIM__PROACTIVE__BEARER_DESCRIPTION__BEARER_TYPE__LOCAL_LINK_TECHNOLOGY_INDEPENDENT = 0x04,
    SWSIM__PROACTIVE__BEARER_DESCRIPTION__BEARER_TYPE__BLUETOOTH = 0x05,
    SWSIM__PROACTIVE__BEARER_DESCRIPTION__BEARER_TYPE__IRDA = 0x06,
    SWSIM__PROACTIVE__BEARER_DESCRIPTION__BEARER_TYPE__RS232 = 0x07,
    SWSIM__PROACTIVE__BEARER_DESCRIPTION__BEARER_TYPE__CDMA2000_PACKET_DATA_SERVICE = 0x08,
    SWSIM__PROACTIVE__BEARER_DESCRIPTION__BEARER_TYPE__RESERVED_GSM_3GPP_2 = 0x09,
    SWSIM__PROACTIVE__BEARER_DESCRIPTION__BEARER_TYPE__RESERVED_3GPP_IWLAN = 0x0A,
    SWSIM__PROACTIVE__BEARER_DESCRIPTION__BEARER_TYPE__RESERVED_3GPP_EUTRAN_NGRAN_SATELLITENGRAN_MAPPEDUTRANPACKETSERVICE = 0x0B,
    SWSIM__PROACTIVE__BEARER_DESCRIPTION__BEARER_TYPE__RESERVED_3GPP_NGRAN_SATELLITENGRAN = 0x0C,
    SWSIM__PROACTIVE__BEARER_DESCRIPTION__BEARER_TYPE__RESERVED_3GPP_FUTURE_USE_0 = 0x0D,
    SWSIM__PROACTIVE__BEARER_DESCRIPTION__BEARER_TYPE__RESERVED_3GPP_FUTURE_USE_1 = 0x0E,
    SWSIM__PROACTIVE__BEARER_DESCRIPTION__BEARER_TYPE__USB = 0x10,
    // clang-format on
} swsim__proactive__bearer_description__bearer_type_et;

/* ETSI TS 102 223 V17.2.0 clause.8.59. */
typedef enum swsim__proactive__uicc_terminal_interface_transport_level__transport_protocol_type_e
{
    // clang-format off
    SWSIM__PROACTIVE__UICC_TERMINAL_INTERFACE_TRANSPORT_LEVEL__TRANSPORT_PROTOCOL_TYPE__UDP_CLIENT_MODE_REMOTE_CONNECTION = 0x01,
    SWSIM__PROACTIVE__UICC_TERMINAL_INTERFACE_TRANSPORT_LEVEL__TRANSPORT_PROTOCOL_TYPE__TCP_CLIENT_MODE_REMOTE_CONNECTION = 0x02,
    SWSIM__PROACTIVE__UICC_TERMINAL_INTERFACE_TRANSPORT_LEVEL__TRANSPORT_PROTOCOL_TYPE__TCP_SERVER_MODE = 0x03,
    SWSIM__PROACTIVE__UICC_TERMINAL_INTERFACE_TRANSPORT_LEVEL__TRANSPORT_PROTOCOL_TYPE__UDP_CLIENT_MODE_LOCAL_CONNECTION = 0x04,
    SWSIM__PROACTIVE__UICC_TERMINAL_INTERFACE_TRANSPORT_LEVEL__TRANSPORT_PROTOCOL_TYPE__TCP_CLIENT_MODE_LOCAL_CONNECTION = 0x05,
    SWSIM__PROACTIVE__UICC_TERMINAL_INTERFACE_TRANSPORT_LEVEL__TRANSPORT_PROTOCOL_TYPE__DIRECT_COMMUNICATION_CHANNEL = 0x06,
    // clang-format on
} swsim__proactive__uicc_terminal_interface_transport_level__transport_protocol_type_et;

/* ETSI TS 102 223 V17.2.0 clause.8.58. */
typedef enum swsim__proactive__other_address__address_type_e
{
    // clang-format off
    SWSIM__PROACTIVE__OTHER_ADDRESS__ADDRESS_TYPE__IPV4 = 0x21,
    SWSIM__PROACTIVE__OTHER_ADDRESS__ADDRESS_TYPE__IPV6 = 0x57,
    // clang-format on
} swsim__proactive__other_address__address_type_et;

/* ETSI TS 102 223 V17.2.0 clause.8.1. */
typedef enum swsim__proactive__address__type_of_number_e
{
    // clang-format off
    SWSIM__PROACTIVE__ADDRESS__TYPE_OF_NUMBER__UNKNOWN = 0b000,
    SWSIM__PROACTIVE__ADDRESS__TYPE_OF_NUMBER__INTERNATIONAL_NUMBER = 0b001,
    SWSIM__PROACTIVE__ADDRESS__TYPE_OF_NUMBER__NATIONAL_NUMBER = 0b010,
    SWSIM__PROACTIVE__ADDRESS__TYPE_OF_NUMBER__NETWORK_SPECIFIC_NUMBER = 0b011,
    // clang-format on
} swsim__proactive__address__type_of_number_et;

/* ETSI TS 102 223 V17.2.0 clause.8.1. */
typedef enum swsim__proactive__address__numbering_plan_identification_e
{
    // clang-format off
    SWSIM__PROACTIVE__ADDRESS__NUMBERING_PLAN_IDENTIFICATION__UNKNOWN = 0b0000,
    SWSIM__PROACTIVE__ADDRESS__NUMBERING_PLAN_IDENTIFICATION__ISDN_TELEPHONY_NUMBERING_PLAN = 0b0001,
    SWSIM__PROACTIVE__ADDRESS__NUMBERING_PLAN_IDENTIFICATION__DATA_NUMBERING_PLAN = 0b0011,
    SWSIM__PROACTIVE__ADDRESS__NUMBERING_PLAN_IDENTIFICATION__TELEX_NUMBERING_PLAN = 0b0100,
    SWSIM__PROACTIVE__ADDRESS__NUMBERING_PLAN_IDENTIFICATION__PRIVATE_NUMBERING_PLAN = 0b1001,
    SWSIM__PROACTIVE__ADDRESS__NUMBERING_PLAN_IDENTIFICATION__RESERVED_FOR_EXTENSION = 0b1111,
    // clang-format on
} swsim__proactive__address__numbering_plan_identification_et;

/* ETSI TS 102 223 V17.2.0 clause.8.68. */
typedef enum swsim__proactive__remote_entity_address__coding_type_e
{
    // clang-format off
    SWSIM__PROACTIVE__REMOTE_ENTITY_ADDRESS__CODING_TYPE__IEEE_802_16_2009_ADDRESS_48BIT = 0x00,
    SWSIM__PROACTIVE__REMOTE_ENTITY_ADDRESS__CODING_TYPE__IRDA_DEVICE_ADDRESS_32BIT = 0x01,
    // clang-format on
} swsim__proactive__remote_entity_address__coding_type_et;

/* ETSI TS 102 223 V17.2.0 clause.8.2. */
typedef struct swsim__proactive__tlv__alpha_identifier_s
{
    bool valid;
    char const *alpha_identifier;
} swsim__proactive__tlv__alpha_identifier_st;

/* ETSI TS 102 223 V17.2.0 clause.8.7. */
typedef struct swsim__proactive__tlv__device_identities_s
{
    bool valid;
    swsim__proactive__device_identities__type_et source;
    swsim__proactive__device_identities__type_et destination;
} swsim__proactive__tlv__device_identities_st;

/* ETSI TS 102 223 V17.2.0 clause.8.15. */
typedef struct swsim__proactive__tlv__text_string_s
{
    bool valid;
    swsim__proactive__text_string__data_coding_scheme_et data_coding_scheme;
    char const *text_string;
} swsim__proactive__tlv__text_string_st;

/* ETSI TS 102 223 V17.2.0 clause.8.31. */
typedef struct swsim__proactive__tlv__icon_identifier_s
{
    bool valid;
    swsim__proactive__icon_identifier__icon_qualifier_et icon_qualifier;
    /**
     * "The icon identifier addresses a record in EF.IMG as defined in ETSI
     * TS 131 102."
     * ETSI TS 102 223 V17.2.0 clause 8.31.
     */
    uint8_t icon_identifier;
} swsim__proactive__tlv__icon_identifier_st;

/* ETSI TS 102 223 V17.2.0 clause.8.43. */
typedef struct swsim__proactive__tlv__immediate_response_s
{
    bool valid;
} swsim__proactive__tlv__immediate_response_st;

/* ETSI TS 102 223 V17.2.0 clause.8.8. */
typedef struct swsim__tlv__proactive__duration_s
{
    bool valid;
    swsim__proactive__duration__time_unit_et time_unit;
    uint8_t time_interval;
} swsim__proactive__tlv__duration_st;

/* ETSI TS 123 040 V17.3.0 clause.3.10.1. */
typedef struct swsim__proactive__tlv__text_attribute__text_formatting_s
{
    uint8_t start_offset; /* Offset after which to start applying formatting. */
    uint8_t length;       /* Length of text to format. */
    swsim__proactive__text_attribute__formatting_style_et style;
    swsim__proactive__text_attribute__color_et color;
} swsim__proactive__tlv__text_attribute__text_formatting_st;
/* ETSI TS 102 223 V17.2.0 clause.8.72. */
typedef struct swsim__proactive__tlv__text_attribute_s
{
    bool valid;
    uint8_t text_formatting_count;
    /**
     * ETSI TS 123 040 V17.3.0 clause.9.2.3.24.10.1.1.
     */
    swsim__proactive__tlv__text_attribute__text_formatting_st const
        *text_formatting;
} swsim__proactive__tlv__text_attribute_st;

/* ETSI TS 102 223 V17.2.0 clause.8.80. */
typedef struct swsim__proactive__tlv__frame_identifier_s
{
    bool valid;
    uint8_t frame_identifier; /* Between 0x00 and 0x0F, 0x00 means entire screen
                                 and 0x10 to 0xFF is RFU. */
} swsim__proactive__tlv__frame_identifier_st;

/* ETSI TS 102 223 V17.2.0 clause.8.9. */
typedef struct swsim__proactive__tlv__item_s
{
    bool valid;
    uint8_t item_identifier; /* Between 0x01 and 0xFF. Every item must be unique
                                but order doesn't matter. */
    char const *item_text_string;
} swsim__proactive__tlv__item_st;

/* ETSI TS 102 223 V17.2.0 clause.8.24. */
typedef struct swsim__proactive__tlv__item_next_action_indicator_s
{
    bool valid;
    uint8_t item_next_action_indcator_count;
    uint8_t const
        *item_next_action_indicator_list; /* 0x00 in this list causes the item
                                              to not be listed. */
} swsim__proactive__tlv__item_next_action_indicator_st;

/* ETSI TS 102 223 V17.2.0 clause.8.48. */
typedef struct swsim__proactive__tlv__url_s
{
    bool valid;
    char const *const
        url; /* Coded as IETF RFC 1738 using the GSM 7bit default alphabet. */
} swsim__proactive__tlv__url_st;

/* ETSI TS 102 223 V17.2.0 clause.8.49. */
typedef struct swsim__proactive__tlv__bearer_s
{
    bool valid;
    swsim__proactive__bearer__bearer_et const *bearer;
} swsim__proactive__tlv__bearer_st;

/* ETSI TS 102 223 V17.2.0 clause.8.50. */
typedef struct swsim__proactive__tlv__provisioning_file_reference_s
{
    bool valid;
    uint16_t const *path;
} swsim__proactive__tlv__provisioning_file_reference_st;

/* ETSI TS 102 223 V17.2.0 clause.8.70. */
typedef struct swsim__proactive__tlv__network_access_name_s
{
    bool valid;
    uint8_t const network_access_name_length;
    uint8_t const *network_access_name; /* At least 3 bytes long. */
} swsim__proactive__tlv__network_access_name_st;

/* ETSI TS 102 223 V17.2.0 clause.8.47. */
typedef struct swsim__proactive__tlv__browser_identity_s
{
    bool valid;
    swsim__proactive__browser_identity__browser_identity_et browser_identity;
} swsim__proactive__tlv__browser_identity_st;

/* ETSI TS 102 223 V17.2.0 clause.8.32. */
typedef struct swsim__proactive__tlv__item_icon_identifier_list_s
{
    bool valid;
    swsim__proactive__item_icon_identifier_list__icon_list_qualifier_et
        icon_list_qualifier;
    uint8_t icon_identifier_count;
    uint8_t const *icon_identifier_list;
} swsim__proactive__tlv__item_icon_identifier_list_st;

/* ETSI TS 102 223 V17.2.0 clause.8.73. */
typedef struct swsim__proactive__tlv__item_text_attribute_list_s
{
    bool valid;
    uint8_t text_formatting_count;
    swsim__proactive__tlv__text_attribute__text_formatting_st const
        *text_formatting;
} swsim__proactive__tlv__item_text_attribute_list_st;

/* ETSI TS 102 223 V17.2.0 clause.8.16. */
typedef struct swsim__proactive__tlv__tone_s
{
    bool valid;
    swsim__proactive__tone__tone_et tone;
} swsim__proactive__tlv__tone_st;

/* ETSI TS 102 223 V17.2.0 clause.8.52. */
typedef struct swsim__proactive__tlv__bearer_description_s
{
    bool valid;
    swsim__proactive__bearer_description__bearer_type_et bearer_type;
    uint8_t bearer_parameter_count;
    uint8_t const *bearer_parameter;
} swsim__proactive__tlv__bearer_description_st;

/* ETSI TS 102 223 V17.2.0 clause.8.55. */
typedef struct swsim__proactive__tlv__buffer_size_s
{
    bool valid;
    uint16_t buffer_size;
    /**
     * When sent by UICC, indicates how many bytes are requested from the
     * terminal. When sent by the terminal in TERMINAL RESPONSE, indicates how
     * many bytes are available.
     */
} swsim__proactive__tlv__buffer_size_st;

/* ETSI TS 102 223 V17.2.0 clause.8.59. */
typedef struct swsim__proactive__tlv__uicc_terminal_interface_transport_level_s
{
    bool valid;
    swsim__proactive__uicc_terminal_interface_transport_level__transport_protocol_type_et
        transport_protocol_type;
    uint16_t port_number;
} swsim__proactive__tlv__uicc_terminal_interface_transport_level_st;

/* ETSI TS 102 223 V17.2.0 clause.8.58. */
typedef struct swsim__proactive__tlv__other_address_s
{
    bool valid;

    /**
     * A null Local address shall be coded with Length = '00', and no Value
     * part. In that case, the terminal shall request a dynamic address; the
     * type of address and the address shall be provided by the terminal (placed
     * in TERMINAL RESPONSE).
     */
    bool null;

    swsim__proactive__other_address__address_type_et address_type;
    union {
        uint8_t ipv4[4];
        uint8_t ipv6[16];
    };
} swsim__proactive__tlv__other_address_st;

/* ETSI TS 102 223 V17.2.0 clause.8.1. */
typedef struct swsim__proactive__tlv__address_s
{
    bool valid;
    swsim__proactive__address__type_of_number_et type_of_number;
    swsim__proactive__address__numbering_plan_identification_et
        numbering_plan_identification;
    uint8_t dialing_number_length;
    uint8_t const *dialing_number;
} swsim__proactive__tlv__address_st;

/* ETSI TS 102 223 V17.2.0 clause.8.3. */
typedef struct swsim__proactive__tlv__subaddress_s
{
    bool valid;

    /**
     * XXX: Per ETSI TS 131 102 V17.10.0 clause.4.4.2.3, there is also an alpha
     * identifier before the rest of the items. Problem is that the length of
     * the dialing number/SSC string is determined from the length of the data
     * object, but the alpha identifier can have variable length which makes
     * that impossible. This is why the alpha identifier is omitted here.
     */

    swsim__proactive__address__type_of_number_et type_of_number;
    swsim__proactive__address__numbering_plan_identification_et
        numbering_plan_identification;
    uint8_t dialing_number_ssc[10];

    /**
     * Record in EF_CCP1 containing associated capability/configuration
     * parameters required for the call. If unused, set to 0xFF.
     */
    uint8_t capability_configuration1_record_identifier;

    /**
     * Record in the EF_EXT1 containing an associated called party subaddress or
     * additional data. If unused, set to 0xFF.
     */
    uint8_t extension1_record_identifier;
} swsim__proactive__tlv__subaddress_st;

/* ETSI TS 102 223 V17.2.0 clause.8.68. */
typedef struct swsim__proactive__tlv__remote_entity_address_s
{
    bool valid;
    swsim__proactive__remote_entity_address__coding_type_et coding_type;
    union {
        uint8_t ieee_802_16_2009[6];
        uint8_t irda[4];
    };
} swsim__proactive__tlv__remote_entity_address_st;

/* ETSI TS 102 223 V17.2.0 clause.8.4. */
typedef struct swsim__proactive__tlv__capability_configuration_parameters_s
{
    bool valid;
    uint8_t capability_configuration_parameters_length;
    uint8_t const *capability_configuration_parameters;
} swsim__proactive__tlv__capability_configuration_parameters_st;

/* ETSI TS 102 223 V17.2.0 clause.6.6.1. */
typedef struct swsim__proactive__command__display_text_s
{
    swsim__proactive__tlv__text_string_st text_string;
    swsim__proactive__tlv__icon_identifier_st icon_identifier;
    swsim__proactive__tlv__immediate_response_st immediate_response;
    swsim__proactive__tlv__duration_st duration;
    swsim__proactive__tlv__text_attribute_st text_attribute;
    swsim__proactive__tlv__frame_identifier_st frame_identifier;
} swsim__proactive__command__display_text_st;

/* ETSI TS 102 223 V17.2.0 clause.6.6.7. */
typedef struct swsim__proactive__command__set_up_menu_s
{
    swsim__proactive__tlv__alpha_identifier_st alpha_identifier;
    uint8_t item_count;
    swsim__proactive__tlv__item_st const *item;
    swsim__proactive__tlv__item_next_action_indicator_st
        item_next_action_indicator;
    swsim__proactive__tlv__icon_identifier_st icon_identifier;
    swsim__proactive__tlv__item_icon_identifier_list_st
        item_icon_identifier_list;
    swsim__proactive__tlv__text_attribute_st text_attribute;
    swsim__proactive__tlv__item_text_attribute_list_st item_text_attribute_list;
} swsim__proactive__command__set_up_menu_st;

/* ETSI TS 102 223 V17.2.0 clause.6.6.26. */
typedef struct swsim__proactive__command__launch_browser_s
{
    swsim__proactive__tlv__browser_identity_st browser_identity;
    swsim__proactive__tlv__url_st url;
    swsim__proactive__tlv__bearer_st bearer;
    uint8_t provisioning_file_reference_count;
    swsim__proactive__tlv__provisioning_file_reference_st const
        *provisioning_file_reference;
    swsim__proactive__tlv__text_string_st text_string_gateway_proxy_identity;
    swsim__proactive__tlv__alpha_identifier_st
        alpha_identifier_user_confirmation_phase;
    swsim__proactive__tlv__icon_identifier_st icon_identifier;
    swsim__proactive__tlv__text_attribute_st text_attribute;
    swsim__proactive__tlv__frame_identifier_st frame_identifier;
    swsim__proactive__tlv__network_access_name_st network_access_name;
    swsim__proactive__tlv__text_string_st text_string_user_login;
    swsim__proactive__tlv__text_string_st text_string_user_password;
} swsim__proactive__command__launch_browser_st;

/* ETSI TS 102 223 V17.2.0 clause.6.6.5. */
typedef struct swsim__proactive__command__play_tone_s
{
    swsim__proactive__tlv__alpha_identifier_st alpha_identifier;
    swsim__proactive__tlv__tone_st tone;
    swsim__proactive__tlv__duration_st duration;
    swsim__proactive__tlv__icon_identifier_st icon_identifier;
    swsim__proactive__tlv__text_attribute_st text_attribute;
    swsim__proactive__tlv__frame_identifier_st frame_identifier;
} swsim__proactive__command__play_tone_st;

typedef enum swsim__proactive__command__open_channel__type_e
{
    SWSIM__PROACTIVE__COMMAND__OPEN_CHANNEL__TYPE__CS_BEARER,
    SWSIM__PROACTIVE__COMMAND__OPEN_CHANNEL__TYPE__PACKET_DATA_SERVICE_BEARER,
    SWSIM__PROACTIVE__COMMAND__OPEN_CHANNEL__TYPE__LOCAL_BEARER,
    SWSIM__PROACTIVE__COMMAND__OPEN_CHANNEL__TYPE__DEFAULT_NETWORK_BEARER,
} swsim__proactive__command__open_channel__type_e;
/* ETSI TS 102 223 V17.2.0 clause.. */
typedef struct swsim__proactive__command__open_channel_s
{
    swsim__proactive__tlv__alpha_identifier_st alpha_identifier;
    swsim__proactive__tlv__icon_identifier_st icon_identifier;
    swsim__proactive__tlv__bearer_description_st bearer_description;
    swsim__proactive__tlv__buffer_size_st buffer_size;
    swsim__proactive__tlv__text_string_st text_string_user_password;
    swsim__proactive__tlv__uicc_terminal_interface_transport_level_st
        uicc_terminal_interface_transport_level;
    swsim__proactive__tlv__other_address_st data_destination_address;
    swsim__proactive__tlv__text_attribute_st text_attribute;
    swsim__proactive__tlv__frame_identifier_st frame_identifier;

    swsim__proactive__command__open_channel__type_e type;
    union {
        struct
        {
            swsim__proactive__tlv__address_st address;
            swsim__proactive__tlv__subaddress_st subaddress;
            swsim__proactive__tlv__duration_st duration1;
            swsim__proactive__tlv__duration_st duration2;
            swsim__proactive__tlv__other_address_st other_address_local_address;
            swsim__proactive__tlv__text_string_st text_string_user_login;
        } cs_bearer;
        struct
        {
            swsim__proactive__tlv__other_address_st other_address_local_address;
            swsim__proactive__tlv__text_string_st text_string_user_login;
            swsim__proactive__tlv__network_access_name_st network_access_name;
        } packet_data_service_bearer;
        struct
        {
            swsim__proactive__tlv__duration_st duration1;
            swsim__proactive__tlv__duration_st duration2;
            swsim__proactive__tlv__remote_entity_address_st
                remote_entity_address;
        } local_bearer;
        struct
        {
            swsim__proactive__tlv__other_address_st other_address_local_address;
            swsim__proactive__tlv__text_string_st text_string_user_login;
        } default_network_bearer;
    };
} swsim__proactive__command__open_channel_st;

/* ETSI TS 102 223 V17.2.0 clause.6.6.12. */
typedef struct swsim__proactive__command__set_up_call_s
{
    /* clang-format off */
    swsim__proactive__tlv__alpha_identifier_st alpha_identifier__user_confirmation_phase;
    swsim__proactive__tlv__address_st address;
    /* NOTE: If caps config params are missing, speech call is assumed. */
    swsim__proactive__tlv__capability_configuration_parameters_st capability_configuration_parameters;
    swsim__proactive__tlv__subaddress_st subaddress;
    /* NOTE: If duration is missing, UICC imposes no restrictions on the terminal of the maximum duration of redials. */
    swsim__proactive__tlv__duration_st duration;
    swsim__proactive__tlv__icon_identifier_st icon_identifier__user_confirmation_phase;
    swsim__proactive__tlv__alpha_identifier_st alpha_identifier__call_set_up_phase;
    swsim__proactive__tlv__icon_identifier_st icon_identifier__call_set_up_phase;
    swsim__proactive__tlv__text_attribute_st text_attribute__user_confirmation_phase;
    swsim__proactive__tlv__text_attribute_st text_attribute__call_set_up_phase;
    swsim__proactive__tlv__frame_identifier_st frame_identifier;
    /* clang-format on */
} swsim__proactive__command__set_up_call_st;

typedef struct swsim__proactive__command_s
{
    /**
     * The command number is basically RFU. It is an ID for the command so that
     * more than one command can be running at the same time.
     * ETSI TS 102 223 V17.2.0 clause 6.5.1
     */
    uint8_t command_number;
    swsim__proactive__command_type_et command_type;
    swsim__proactive__command_details__command_qualifier_et command_qualifier;
    swsim__proactive__tlv__device_identities_st device_identities;

    union {
        swsim__proactive__command__display_text_st display_text;
        swsim__proactive__command__set_up_menu_st set_up_menu;
        swsim__proactive__command__launch_browser_st launch_browser;
        swsim__proactive__command__play_tone_st play_tone;
        swsim__proactive__command__open_channel_st open_channel;
        swsim__proactive__command__set_up_call_st set_up_call;
    };
} swsim__proactive__command_st;

typedef struct swsim__proactive_s swsim__proactive_st;
typedef swicc_ret_et sim__proactive__step_ft(
    swsim__proactive_st *const proactive);
typedef void sim__proactive__init_ft(swsim__proactive_st *const proactive);
typedef swicc_ret_et sim__proactive__envelope_ft(
    swsim__proactive_st *const proactive);
typedef swicc_ret_et sim__proactive__terminal_response_ft(
    swsim__proactive_st *const proactive);

typedef struct swsim__proactive_s
{
    uint32_t command_count;

    uint8_t command[SWICC_DATA_MAX];
    uint16_t command_length;
    uint8_t response[SWICC_DATA_MAX];
    uint16_t response_length;
    uint8_t envelope[SWICC_DATA_MAX];
    uint16_t envelope_length;

    bool app_default_enable;
    bool app_default_response_wait;
    struct
    {
        uint8_t select_screen_last;
        uint8_t select_screen_new;
    } app_default;

    bool app_proprietary_enable;
    bool app_proprietary_response_wait;
    void *app_proprietary;
    sim__proactive__init_ft *app_proprietary__init;
    sim__proactive__envelope_ft *app_proprietary__envelope;
    sim__proactive__step_ft *app_proprietary__step;
    sim__proactive__terminal_response_ft *app_proprietary__terminal_response;
} swsim__proactive_st;

sim__proactive__init_ft proactive_init;
sim__proactive__envelope_ft proactive_app_default__envelope;
sim__proactive__step_ft proactive_step;
sim__proactive__terminal_response_ft proactive_app_default__terminal_response;
